spring:
  # Redis
  redis:
    host: 139.224.113.113
    port: 60001
    # 连接超时时间（毫秒）
    timeout: 2000
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        # 连接池中的最小空闲连接
        min-idle: 3
server:
  port: 8082
