rsa:
  encrypt:
    open: true # 是否开启加密 true  or  false
    showLog: true # 是否打印加解密log true  or  false
    timestampCheck: true # 是否开启时间戳检查 ture or false
    publicKey: 1231231
    privateKey: 123123123